Repository CollectingBox/server, pull requests merged in 2024-04, with the labels that each got.

#3 패키지 구조 생성, 엔티티 개발
  scripts/gh_deploy.sh
  src/main/java/contest/collectingbox/CollectingBoxApplication.java
  src/main/java/contest/collectingbox/controller/testController.java
  src/main/java/contest/collectingbox/entity/TestEntity.java
  src/main/java/contest/collectingbox/global/common/BaseTimeEntity.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBox.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepository.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/Tag.java
  src/main/java/contest/collectingbox/module/location/domain/Address.java
  src/main/java/contest/collectingbox/module/location/domain/Location.java
  src/main/java/contest/collectingbox/module/location/domain/LocationRepository.java
  src/main/java/contest/collectingbox/module/review/domain/Review.java
  src/main/java/contest/collectingbox/module/review/domain/ReviewRepository.java
  src/main/java/contest/collectingbox/module/review/domain/Tag.java
  src/test/java/contest/collectingbox/CollectingBoxApplicationTests.java
Labels: feature

#15 응답 형식 개선
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
Labels: refactor

#11 수거함 상세정보 조회 기능 구현
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepository.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryCustom.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryImpl.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/Tag.java
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxDetailResponse.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewResponse.java
  src/test/java/contest/collectingbox/module/collectingbox/application/CollectingBoxServiceTest.java
Labels: feature

#22 수거함 리뷰 등록 기능 구현
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryImpl.java
  src/main/java/contest/collectingbox/module/review/application/ReviewService.java
  src/main/java/contest/collectingbox/module/review/domain/Review.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewRequest.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewResponse.java
  src/main/java/contest/collectingbox/module/review/presentation/ReviewController.java
Labels: feature

#17 Swagger 설정
  build.gradle
  src/main/java/contest/collectingbox/module/autocomplete/application/AutoCompleteService.java
  src/main/java/contest/collectingbox/module/autocomplete/dto/AutoCompleteResponseDto.java
  src/main/java/contest/collectingbox/module/autocomplete/presentation/AutoCompleteController.java
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxResponse.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
Labels: chore, docs

#26 Review API Swagger 설정 추가
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxDetailResponse.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewRequest.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewResponse.java
  src/main/java/contest/collectingbox/module/review/presentation/ReviewController.java
Labels: chore

#23 검색어 자동완성 포맷 수정
  src/main/java/contest/collectingbox/module/autocomplete/application/AutoCompleteService.java
  src/test/java/contest/collectingbox/module/autocomplete/application/AutoCompleteServiceTest.java
Labels: fix

#31 예외 처리 로직 기본 코드 작성
  src/main/java/contest/collectingbox/global/common/ApiResponse.java
  src/main/java/contest/collectingbox/global/exception/CollectingBoxException.java
  src/main/java/contest/collectingbox/global/exception/ErrorCode.java
  src/main/java/contest/collectingbox/global/exception/ErrorResponse.java
  src/main/java/contest/collectingbox/global/exception/GlobalExceptionHandler.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
Labels: feature

#32 CORS 설정 클래스 작성
  src/main/java/contest/collectingbox/global/config/WebConfig.java
Labels: chore, deploy

#40 지역별 수거함 검색 기능 예외 처리
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepository.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
Labels: feature

#37 수거함 목록 조회 기능 예외 처리
  src/main/java/contest/collectingbox/global/exception/ErrorCode.java
  src/main/java/contest/collectingbox/global/exception/GlobalExceptionHandler.java
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/presentation/CollectingBoxController.java
Labels: feature

#43 수거함 상세보기 조회 기능 예외처리
  src/main/java/contest/collectingbox/global/common/DateUtils.java
  src/main/java/contest/collectingbox/global/exception/ErrorCode.java
  src/main/java/contest/collectingbox/global/exception/GlobalExceptionHandler.java
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryImpl.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/Tag.java
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxDetailResponse.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewResponse.java
  src/test/java/contest/collectingbox/module/collectingbox/application/CollectingBoxServiceTest.java
Labels: feature

#41 수거함 리뷰 작성 기능 예외 작성
  src/main/java/contest/collectingbox/global/exception/ErrorCode.java
  src/main/java/contest/collectingbox/global/exception/ErrorResponse.java
  src/main/java/contest/collectingbox/global/exception/GlobalExceptionHandler.java
  src/main/java/contest/collectingbox/module/review/application/ReviewService.java
  src/main/java/contest/collectingbox/module/review/dto/ReviewRequest.java
  src/main/java/contest/collectingbox/module/review/presentation/ReviewController.java
Labels: feature

#53 수거함 상세정보 조회 시 위도, 경도 추가
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryImpl.java
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxDetailResponse.java
  src/test/java/contest/collectingbox/module/collectingbox/application/CollectingBoxServiceTest.java
Labels: feature

#58 카카오 주소 검색 API 호출 로직 마무리
  src/main/java/contest/collectingbox/module/publicdata/AddressInfoResponse.java
  src/main/java/contest/collectingbox/module/publicdata/KakaoApiManager.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataExtract.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataService.java
Labels: feature

#64 공공데이터 DB 저장 기능 구현
  src/main/java/contest/collectingbox/module/publicdata/AddressInfoResponse.java
Labels: feature

#71 공공데이터 정보 빈 값 체크 로직 구현
  src/main/java/contest/collectingbox/module/publicdata/AddressInfoResponse.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataService.java
Labels: feature

#73 시/군/구 매칭 로직 구현
  src/main/java/contest/collectingbox/module/publicdata/LoadCsvPublicDataRequest.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataApiController.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataService.java
Labels: feature

#74 검색어 자동완성 중복 문제 해결
  src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
Labels: fix

#76 폐형광등, 폐건전지 태그 통합 구현
  src/main/java/contest/collectingbox/module/collectingbox/domain/Tag.java
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxResponse.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/contest/collectingbox/module/collectingbox/application/CollectingBoxServiceTest.java
Labels: feature
