Repository CollectingBox/server, pull requests merged in 2024-05, with the labels that each got.

#79 수거함 목록 조회 API 태그 전달 형식 변경
  src/main/java/contest/collectingbox/module/collectingbox/dto/CollectingBoxResponse.java
Labels: feature

#77 공공데이터 키워드 추출시 특이 케이스 처리 구현
  src/main/java/contest/collectingbox/module/publicdata/PublicDataExtract.java
  src/main/java/contest/collectingbox/module/publicdata/PublicDataService.java
Labels: feature

#81 카카오 API 응답값 DB 저장시 행정동으로 저장하도록 변경
  src/main/java/contest/collectingbox/module/publicdata/KakaoApiManager.java
Labels: feature

#82 logback 설정 파일 추가
  build.gradle
  src/main/resources/logback-spring.xml
  src/main/resources/logback/console-appender.xml
  src/main/resources/logback/file-info-appender.xml
Labels: chore

#88 검색어 자동완성 구와 동으로만 검색되도록 수정
  src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
Labels: bug

#90 검색어 자동완성시 dong_info 테이블에서 조회하도록 수정
  src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
Labels: feature

#92 행정동 테이블 분리로 인한 지역별 수거함 검색 기능 개선
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepository.java
  src/main/java/contest/collectingbox/module/location/domain/DongInfoRepository.java
  src/main/java/contest/collectingbox/module/location/domain/LocationRepository.java
Labels: feature

#94 수거함 상세 조회 시 성능 개선
  src/main/java/contest/collectingbox/module/collectingbox/application/CollectingBoxService.java
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepositoryImpl.java
  src/test/java/contest/collectingbox/module/collectingbox/application/CollectingBoxServiceTest.java
Labels: feature

#96 수거함 위도,경도 별 목록 조회 시 N+1 문제 해결
  .gitignore
  src/main/java/contest/collectingbox/module/collectingbox/domain/CollectingBoxRepository.java
Labels: feature

#98 검색어 자동완성시 구, 동 포함한 검색어 인식 구현
  src/main/java/contest/collectingbox/module/autocomplete/application/AutoCompleteService.java
  src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryCustom.java
  src/main/java/contest/collectingbox/module/autocomplete/domain/AutoCompleteRepositoryImpl.java
  src/main/java/contest/collectingbox/module/autocomplete/presentation/AutoCompleteController.java
  src/test/java/contest/collectingbox/module/autocomplete/application/AutoCompleteServiceTest.java
Labels: bug

#100 예외 처리 응답 포맷 수정
  src/main/java/contest/collectingbox/global/common/ApiResponse.java
  src/main/java/contest/collectingbox/global/exception/CollectingBoxException.java
  src/main/java/contest/collectingbox/global/exception/ErrorCode.java
  src/main/java/contest/collectingbox/global/exception/ErrorResponse.java
  src/main/java/contest/collectingbox/global/exception/GlobalExceptionHandler.java
Labels: refactor
